# Generated by Django 4.2.1 on 2023-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
