# Generated by Django 4.2.1 on 2023-06-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_last_modification_date'),
        ('app', '0003_shareditem'),
    ]

    operations = [
    ]
