# Generated by Django 4.2.1 on 2023-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20230606_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password_score',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
