# Generated by Django 4.2.1 on 2023-06-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_password_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
